### ISSUE TITLE
[suggestion] Moving the computed property to a getter

### ISSUE THREAD

**Issue by willylatorre** [soixantecircuits/idle-vue#13]
Hey,
Awesome job with `idle-vue`! 

I don't understand why you are injecting a computed property to every Vue object.
Why don't you create a getter `isAppIdle` in the store and let us subscribe to that value? That would be way more flexible & practical ;)

Thanks a lot!

**Comment by PoignardAzur** [comment]
@willylatorre Thank you very much!

There is already a `idleVue.isIdle` property in the store; you can access it for free. I guess I could remove the isAppIdle computed property, but I doubt it will cause many collisions, and it's faster to type in `v-if` directives.

**Comment by willylatorre** [comment]
Yeah, I know, but a lot of people work with `getters` instead of the whole `store`. Plus, the getter will act as a computed property as defined in the [docs of vuex](https://vuex.vuejs.org/en/getters.html) and it will be faster to type in the `v-if` directives as you say.

Basically, we do have getters to avoid creating this type of computed property!

**Comment by PoignardAzur** [comment]
I've thought about it, and I think I'll leave the system as-is. Accessing the `store`'s states doesn't incur any overhead as far as I'm aware; and having a computed property baked-in is easier who want the module to "just work" with a few configuration as possible (for instance, without having to use `mapGetters` in every component).

I understand that this isn't the most elegant solution, but this is a low-scale module, and elegance isn't as important as it being fast and intuitive to use.

I may remove the computed property and make accessing store states the only solution if I realise it's confusing users.
