### ISSUE TITLE
Error from uglifyJs

### ISSUE THREAD

**Issue by Gerche** [soixantecircuits/idle-vue#17]
I added idle-vue with npm to my vue project and everything was working fine in `run dev` but when i tried to build my project I got the following error:

`ERROR in static/js/vendor.87bf41a35bd9b3a1e693.js from UglifyJs
Unexpected token: punc (() [./~/idle-vue/dist/build.js:678,0][static/js/vendor.87bf41a35bd9b3a1e693.js:12395,9]
`

Did anyone else experience this? I tried changing some settings in my .babelrc but I still get the error.

**Comment by joefresco** [comment]
We are experiencing this as well in the build step.
ERROR in static/js/vendor.fd5522c58ed2ecb09836.js from UglifyJs
Unexpected token: punc (() [./~/idle-vue/dist/build.js:678,0]

**Comment by afonso** [comment]
I resolve this problem with this #19
