### ISSUE TITLE
Idle time option

### ISSUE THREAD

**Issue by piterjov** [soixantecircuits/idle-vue#25]
I think idletime option does not work even If I put 500ms.
Any example of implementing this plugin as component and passing custom idle time to it?
I would be grateful
Thanks

**Comment by gabrielstuff** [comment]
Normally you just suply an idle time in *ms*.

`idleTime: 2000`

```
Vue.use(IdleVue, {
  eventEmitter: eventsHub,
  idleTime: 10000
})

const vm = new Vue({
  el: '#app',
  data () {
    return {
      messageStr: 'Hello'
    }
  },
  onIdle() {
    this.messageStr = 'ZZZ'
  },
  onActive() {
    this.messageStr = 'Hello'
  }
})
```

**Comment by gabrielstuff** [comment]
@piterjov does that work for you ?

**Comment by piterjov** [comment]
Hi @gabrielstuff , still not. How can I use it as component?
            <idle-vue></idle-vue> which will listen to those events from above?
Thanks

**Comment by gabrielstuff** [comment]
No real life example shared.
Closing.

**Comment by flourigh** [comment]
how pass a time per component using a main.js? need put a script inside a component?
![image](https://user-images.githubusercontent.com/722723/90670860-368dfc00-e22a-11ea-81c1-eb52f6827be5.png)
