### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by maciz84** [soixantecircuits/idle-vue#30]
Hi Guys,

Do you have typescript support? When I try following the example it tells me that on onIdle() is not a function?

**Comment by vip30** [comment]
Vue.use(IdleVue, {
  store,
  idleTime: 500
})

**Comment by vip30** [comment]
```
declare module 'idle-vue' {
  import { PluginFunction } from 'vue'
  export interface IdleVueUseOptions {
    events?: string[]
    eventEmitter?: any
    idleTime?: number
    keepTracking?: boolean
    moduleName?: string
    startAtIdle?: boolean
    store?: any
  }
  module "vue/types/vue" {
    interface Vue {
      isAppIdle: boolean
    }
  }
  export function install(): PluginFunction<IdleVueUseOptions>
}
```

And here is the index.d.ts

**Comment by maciz84** [comment]
Thank you so much for this

**Comment by maciz84** [comment]
Just to confirm, i can use either the index.d.ts or the Vue class component one? Or are they meant to be put together?

**Comment by vip30** [comment]
You need to use that together
D.ts is for the type declaration (so it can pass the compile and the intellisense in Ide will woro)
And the vue class component is for real implmentation

**Comment by maciz84** [comment]
This works perfectly. Thank you so much for your help

**Comment by Luciden** [comment]
Can you tell my what I might be doing wrong? Here's my Main.ts
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import { store } from './store/store';
import * as IdleVue from 'idle-vue';
import Component from 'vue-class-component';

Vue.config.productionTip = false;

// Setup idle-vue
Vue.use(IdleVue, {
    eventEmitter: new Vue(),
    store,
    idleTime: 500
});

Component.registerHooks([
    'onIdle',
    'onActive'
])

/* eslint-disable no-new */
new Vue({
    el: '#app',
    router,
    store,
    components: { App },
    onIdle() {
        console.log('Idle')
    },
    onActive() {
        console.log('Active')
    },
    template: '<App/>',
});

I added idle-vue.d.ts to my src directory root with the contents of your index.d.ts

No errors, nothing happens.

**Comment by vip30** [comment]
FYI, you need to register the hooks before all of your codes.
Can you please try if it work or not?
```
// main.ts (Top)
import './class-component-hooks.ts'

// class-component-hooks.ts
Component.registerHooks([
'onIdle',
'onActive'
])
```

**Comment by Luciden** [comment]
Cool, I'll check it out. We wrote Window.SetTimeout version in the meantime. We need a warning followed by a log out. I suppose I could add a timeout to OnIdle()
