### ISSUE TITLE
Error: 'idleVue_onIdle' of undefined

### ISSUE THREAD

**Issue by piyushbeli** [soixantecircuits/idle-vue#31]
I am using the latest version of the module.

This is how I am installing the module. I do not want to emit the event to all the component so I am omitting the eventHandler here.
`Vue.use(IdleVue, {
    store,
    idleTime: 1*60*60*1000
});`

I would expect that **idleVue_onIdle** event will not be called. But, in the console for each component, I am getting this error. Please see the screenshot here. 
![image](https://user-images.githubusercontent.com/2725624/43774027-526d9f3e-9a65-11e8-84ac-985ae9b3d49e.png)

Just for the side note, I am able to watch the store property "**isAppIdle**" and it's working as expected. But, this console is making the things dirty.

Many thanks
Piyush

**Comment by gabrielstuff** [comment]
Hello!
A bit late. If you can share a codepen or a full example, it could be better to help solves the issue.

**Comment by piyushbeli** [comment]
@gabrielstuff , somehow this issue is not reproducible in our system at this time. It actually got fixed before many months. That might not be the module issue but our code issue but I do not remember what did we do to fix that.

Thanks for replying. I am closing this issue.
