### ISSUE TITLE
what is the actual timer in this? I don't understand

### ISSUE THREAD

**Issue by rconstantine** [soixantecircuits/idle-vue#35]
I'm using this. It's working great. I have it working in a Quasar Framework app. I've been through all of the code here and in idle-js and I still don't see what is actually doing the countdown. What am I missing?

**Comment by gabrielstuff** [comment]
Hello, sorry for being so late. I'm not sure what you are looking for.
This component depends on idle-js. Idle-js bind to the event you decided to listen to. If non of them are triggered during a certain time, then the idle will trigger.

The certain time frame is this timeout.

See: https://github.com/soixantecircuits/idle-js/blob/master/src/Idle.js#L67

**Comment by rconstantine** [comment]
It's been a while since I asked, but I think your link is exactly what I was looking for. I guess I missed it before. Thanks.
