### ISSUE TITLE
Inquiry about tracking the idle users

### ISSUE THREAD

**Issue by ramadan26** [soixantecircuits/idle-vue#51]
I need to listen to a specific button, I've initialized the "events" as 'none'
and when I click on the button I'm changing the value of idleVue.isIdle in the store by committing a mutation:
`this.$store.commit('idleVue/IDLE_CHANGED', false)`
But the issue is, it's stopping to show me that notification after I clicked on that button (reset button).

How to make the package listen to a specific button?

**Comment by gabrielstuff** [comment]
If you want to check on a button, why would you need to use a package with the main is to listen on everything ?
